#!/usr/bin/env bash
set -euo pipefail

echo "==> Building projconf..."
goreleaser release --clean --skip=validate --snapshot

export PROJCONF_ADMIN_ACCESS_KEY="LOCAL-DEVELOPMENT-TEST"

echo "==> Running projconf..."
exec ./dist/projconf_darwin_arm64_v8.0/projconf "$@"