import type { paths } from "./schema";
import CreateClient, { Client as IClient } from "openapi-fetch"; // generated by openapi-typescript

export type { paths, components, operations } from "./schema";

export type Client = IClient<paths>;

type BaseProps = {
  baseURL: string;
}

export type AdminClientProps = BaseProps & {
  adminApiKey: string;
}

export type StandardClientClientProps = BaseProps & {
  client: {
    id: string;
    secret: string;
  }
}

export type CreateClientProps = AdminClientProps | StandardClientClientProps;

export const createClient = (props: CreateClientProps): Client => CreateClient({
  baseUrl: props.baseURL,
  headers: "adminApiKey" in props ? {
    ["x-admin-api-key"]: props.adminApiKey
  } : {
    ["x-client-secret-id"]: props.client.id,
    ["x-client-secret"]: props.client.secret
  }
});
