openapi: 3.0.0
info:
  title: Secrets API
  version: 1.0.0
tags:
  - name: admin
    description: admin API endpoints
  - name: client
    description: client API endpoints
paths:
  /v1/admin/health:
    get:
      tags:
        - admin
      summary: Get health
      description: Returns a health-check on the server
      responses:
        '200':
          description: client object
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /v1/clients/_self:
    get:
      tags:
        - client
      summary: Get self
      description: Returns the client object for the currently-authenticated client.
      responses:
        '200':
          description: client object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                  display:
                    type: string
                  project_id:
                    type: string
                    format: uuid
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /v1/admin/projects:
    post:
      tags:
        - admin
      summary: Create project
      description: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: project name (must be unique)
                  pattern: ^[[:alnum:] _]+$
                  minLength: 1
              required:
                - name
      responses:
        '201':
          description: Project Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /v1/admin/projects/{project_id}/environments:
    post:
      tags:
        - admin
      summary: Create environment
      description: Create a new environment
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the project.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: project name (must be unique)
                  pattern: ^[[:alnum:] _]+$
                  minLength: 1
              required:
                - name
      responses:
        '201':
          description: Environment Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /v1/projects/{project_id}/environments/{environment_id}/secrets:
    get:
      tags:
        - client
      summary: List secrets
      description: Returns all secrets for a given project environment.
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the project.
        - name: environment_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the environment.
      responses:
        '200':
          description: A list of secrets.
          content:
            application/json:
              schema:
                type: object
                properties:
                  secrets:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden