openapi: 3.1.0
info:
  title: Secrets API
  version: 1.0.0
paths:
  /v1/projects/{project_id}/environments/{environment_id}/secrets:
    get:
      summary: List secrets
      description: Returns all secrets for a given project environment.
      security:
        - ClientSecretAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the project.
        - name: environment_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the environment.
      responses:
        '200':
          description: A list of secrets.
          content:
            application/json:
              schema:
                type: object
                properties:
                  secrets:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  securitySchemes:
    ClientSecretAuth:
      type: apiKey
      in: header
      name: x-client-secret-id
      description: |
        Client authentication using a pair of headers:
        - `x-client-secret-id`: The client identifier.
        - `x-client-secret`: The client secret value.
  parameters:
    ClientSecretHeader:
      name: x-client-secret
      in: header
      required: true
      schema:
        type: string
      description: Client secret value.