on:
  push:
    paths:
      - 'version.json'

jobs:
  version:
    uses: train360-corp/actions/.github/workflows/version-check.yml@main
    with:
      file-name: version.json
      json-version-path: .version
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-24.04
    needs:
      - version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build using Makefile
        run: make VERSION=${{ needs.version.outputs.version }}